# Generated by Django 6.0.2 on 2026-03-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_savingsgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(choices=[('$', 'USD ($)'), ('₹', 'INR (₹)'), ('€', 'EUR (€)'), ('£', 'GBP (£)')], default='₹', max_length=5),
        ),
    ]
